sudo: required
services:
 - docker

before_install:
  - docker build -t armaelblack/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run armaelblack/react-test npm run test-coverage -- --coverage

after_success:
  - docker build -t armaelblack/multi-client ./client
  - docker build -t armaelblack/multi-nginx ./nginx
  - docker build -t armaelblack/multi-server ./server
  - docker build -t armaelblack/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push armaelblack/multi-client
  - docker push armaelblack/multi-nginx
  - docker push armaelblack/multi-server
  - docker push armaelblack/multi-worker

deploy:
  provider: elasticbeanstalk
  region: eu-central-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-eu-central-1-856243696161
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: 
    secure: $AWS_SECRET_KEY