sudo: required
services:
 - docker

before_install:
  - docker build -t armaelblack/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run armaelblack/react-test npm run test-coverage -- --coverage

after_success:
  - docker build -t armaelblack/multi-client ./client
  - docker build -t armaelblack/multi-nginx ./nginx
  - docker build -t armaelblack/multi-server ./server
  - docker build -t armaelblack/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push armaelblack/multi-client
  - docker push armaelblack/multi-nginx
  - docker push armaelblack/multi-server
  - docker push armaelblack/multi-worker